config/routes.rb
Rails.application.routes.draw do

   root 'products#index'

   resources :products
   resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, PhotoUploader

  belongs_to :product

  validates :product, presence: true



end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :productimage, ProductimageUploader

  has_many :photos, :inverse_of => :product, :dependent => :destroy
  
  # enable nested attributes for photos through album class
  accepts_nested_attributes_for :photos, allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(photo_params)
    @photo.save
  end

  def destroy
    @photos = Photo.find(params[:id])
    @photos.destroy
    redirect_to edit_product_path(@photos.product) , notice: '照片已刪除'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if params[:images]
        params[:images].each { |image| @product.photos.create(image: image)}
      end
      redirect_to products_path, notice:'新增產品成功'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
  #  render text:params
  #  return
    @product = Product.find(params[:id])
    if @product.update(product_params)
      if params[:images]
        params[:images].each { |image| @product.photos.create(image: image) }
      end

      redirect_to products_path, notice: '產品編輯完成'
    else
      render :edit, notice: 'error'
    end

  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
    redirect_to products_path, notice:'產品已刪除'
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :is_online, :productimage, :remove_productimage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shinlin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <%= f.label :name, '產品名稱' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description, '產品描述' %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :is_online, '是否上線' %>
  <%= f.check_box :is_online %>
  <br>
  <p><%= f.label :productimage, '產品圖片' %></p>
  <%= image_tag(@product.productimage_url) if @product.productimage? %>
  <br>
  <%= f.file_field :productimage %>
  <br>
  <%= f.label :remove_productimage, '刪除' %>
  <%= f.check_box :remove_productimage %>
  <br>
  <%= file_field_tag "images[]", type: :file, multiple: true %>
  <% @product.photos.each do |p| %>
    <%= image_tag(p.image.url) %>
    <%= link_to 'delete', photo_path(p), method: :delete, data: {confirm: '確定刪除'} %>
  <% end %>
  <br>
  <%=  f.submit %>
<% end %>
  

app/views/products/edit.html.erb
編輯產品
<%= render 'form' %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <br>
  <%= link_to product.name, edit_product_path(product) %>
  <%= product.description %>
  <br>
  <%= image_tag product.productimage %>
  <br>
  <% product.photos.each do |image|%>
    <div>
      <%= image_tag image.image.thumb %>
    </div>
    <div>
      <%= image_tag image.image %>
    </div>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= render 'form' %>